server:
  port: 10080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host:port/sns_user?characterEncoding=UTF-8&serverTimezone=UTC
    username: username
    password: password
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      cache:
        use_second_level_cache: true
        use_query_cache: true
        region:
          factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    hibernate:
      ddl-auto: create
